applications:
  app:
    type: "nodejs:22"
    web:
      commands:
        start: "node app.js"
      locations:
        "/":
          passthru: true

routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"